[package]
name = "spacepaint-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.1"
image = "0.25"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "time",
    "macros",
    "sync",
] }
anyhow = "1.0"
