[package]
name = "spacepaint-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["time", "fs", "rt-multi-thread", "macros"] }
log = "0.4"
env_logger = "0.11"
futures = "0.3"
